resources:
  - name: testing_1
    type: gitRepo
    repoPath: vijayreddy1991/pipelinetest
    configuration:
      integrationName: github
      branches:
        only: master
    initialVersion:
      sha: master
  
pipelines:
  - name: pipeline_pipe
    setup:
      environmentVariables:
        readOnly:
          NameF: vijay
          NameL: kumar
    steps:    
      - name: test1
        type: bash
        setup:
          environmentVariables:
            normal:
              Number: 90
#               Name: umar       
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          resources:
            - testing_1
        execution:
          onExecute:
            - echo "hi"
            - printenv
            - echo "NameF=$NameF"

      - name: test2
        type: bash
        setup:
          environmentVariables:
            normal:
              Number: 24
              Sequence: 1         
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - test1
        execution:
          onExecute:
            - echo "test2"
            - printenv
            - echo "NameF=$NameF"

      - name: test3
        type: bash
        setup:
          environmentVariables:
            normal:
              Number: 22
              Sequence: 1        
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - test2
        execution:
          onExecute:
            - echo "Test3"
            - printenv
            - echo "NameF=$NameF"

      - name: test4
        type: bash
        setup:
          environmentVariables:
            normal:
              Number: 29
              Sequence: 1          
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - test3
        execution:
          onExecute:
            - echo "test4"
            - printenv
            - echo "NameF=$NameF"
