resources:
  - name: sample_scriptrepo
    type: gitRepo
    repoPath: vijayreddy1991/sample_pip
    configuration:
      integrationName: github
      branches:
        only: master
      tags:
        except: none
        only: none   
      buildOnCommit: true
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnRelease: true
      buildOnTagPush: true
      buildOnFileCommit: "*test"
      shallowDepth: 2
      gitConfig: 
        - dont_know
        - dont_know_2
    initialVersion:
      sha: master
  
pipelines:
  - name: pipeline_1
    steps:    
      - name: build-test
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          resources:
            - sample_scriptrepo
        execution:
          onExecute:
            - echo "hi"

#       - name: test2
#         type: bash
#         setup:
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           steps:
#             - build-test
#         execution:
#           onExecute:
#             - echo "test2"

#       - name: push-test3
#         type: bash
#         setup:
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         requires:
#           integrations:
#             - artifactorytest
#         triggeredBy:
#           steps:
#             - test2
#         execution:
#           onExecute:
#             - echo "push-Test3"

#       - name: job2
#         type: bash
#         setup:
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           steps:
#             - build-test
#         execution:
#           onExecute:
#             - echo "job2"
