resources:
  - name: sample_scriptrepo
    type: gitRepo
    repoPath: vijayreddy1991/sample_pip
    configuration:
      integrationName: github
      branches:
        only: master
      tags:
        except: none
        only: none   
      buildOnCommit: true
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnRelease: true
      buildOnTagPush: true
      buildOnFileCommit: "*test"
      shallowDepth: 2
      gitConfig: 
        - dont_know
        - dont_know_2
    initialVersion:
      sha: master
  
pipelines:
  - name: pipeline1
    steps:    
      - name: test1
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          resources:
            - sample_scriptrepo
        execution:
          onExecute:
            - echo "hi"

      - name: test2
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - test1
        execution:
          onExecute:
            - echo "test2"

      - name: test3
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - test2
        execution:
          onExecute:
            - echo "Test3"

      - name: test4
        type: bash
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - test3
        execution:
          onExecute:
            - echo "test4"
