resources:
  - name: testing_1
    type: gitRepo
    repoPath: vijayreddy1991/sample_pip
    configuration:
      integrationName: github
      branches:
        only: master
    initialVersion:
      sha: master
  
pipelines:
  - name: pipeline_1
    setup:
      environmentVariables:
        readOnly:
          OLD: vijay
          NEW: kumar
    steps:    
      - name: test1
        type: bash
        setup:
          environmentVariables:
            normal:
              OLD: ranjan
              NEW: reddy        
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          resources:
            - testing_1
        execution:
          onExecute:
            - echo "hi"
            - printenv

      - name: test2
        type: bash
        setup:
          environmentVariables:
            normal:
              FirstV: ranjan
              LastV: reddy         
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - test1
        execution:
          onExecute:
            - echo "test2"
            - printenv

      - name: test3
        type: bash
        setup:
          environmentVariables:
            normal:
              FirstV: ranjan
              LastV: reddy       
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - test2
        execution:
          onExecute:
            - echo "Test3"
            - printenv

      - name: test4
        type: bash
        setup:
          environmentVariables:
            normal:
              FirstV: ranjan
              LastV: reddy         
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - test3
        execution:
          onExecute:
            - echo "test4"
            - printenv
